# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85ca1049adbce30c697b2fd3be0dc96b2a97ba8793ff5c2b51be6c8dc360c14b227a4310f49d35186ddba8ee9455c324d48d5abcbfb9b6edc73479f690690c99

test:
  secret_key_base: 1f09c521f6b6b674e8e8521456e761548d7818ba083653aac0b69b8962513dbf73ed6b3fcf799c7d54eab5b626f6b46862f03a106002ade68223cd45b4b0d0e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
